### ISSUE TITLE
Twitter API - Telefonnummer

### ISSUE THREAD

**Issue by MWin123** [eppleton/javafxbuch#3]
Hallo,

ich habe gestern im Thalia ihr Buch durchgeblättert und anschließend gekauft.

Laut Kapitel 2 haben Sie einen Twitter-Client als Beispielprogramm gewählt, weil Twitter keine "Real Name Policy" hat. Jedoch bekam ich, als ich eine neue App registrieren wollte, folgende Fehlermeldung: "You must add your mobile phone to your Twitter profile before creating an application. Please read [...] for more information"

Daher habe ich im Internet recherchiert und es ist seit circa Anfang 2014 nicht mehr möglich, ohne eine mit dem Account verbundene Telefonnummer die API zu benutzen. Daher habe ich widerwillig meine Telefonnummer angegeben, da ich ohne die API nicht wirklich was mit dem Buch anfangen kann. Leider stellte sich raus, dass man eine österreichische Handynummer nicht per SMS verifizieren kann. Die einzige Möglichkeit war, mehrere SMS mit den Logindaten an eine Telefonnummer in Deutschland zu schicken.

Der ganze Aufwand inklusive Roaminggebühren widerspricht sich mit der Aussage "Sie müssen nicht Ihre echten Daten angeben. [...] Sie brauchen nur eine funktionierende E-Mail-Adresse"

Hätte ich das vorher gewusst, hätte ich das Buch wahrscheinlich nicht gekauft.

**Comment by toni-epple** [comment]
Zu dem Zeitpunkt, als ich das Buch verfasst habe, war das tatsächlich so wie beschrieben. Ich kann das gedruckte Buch leider nicht nachträglich ändern.
