### ISSUE TITLE
Maven Import in IntelliJ IDEA

### ISSUE THREAD

**Issue by MWin123** [eppleton/javafxbuch#4]
Hallo,

ich bin Programmieranfänger und habe keine Erfahrungen mit Maven.

Ich habe das Repository mit GitHub for Windows geklont und wollte es mit IntelliJ IDEA als Maven Projekt importieren.
Wenn ich den Ordner javafxbuch wähle, findet Intellij IDEA kein Maven Projekt. Dann kann ich entweder eine einzelne POM.xml wählen und es wird nur ein Unterkapitel importiert oder ich wähle "Search for projects recursively". Dann findet die IDE zwar alle POM.xml Dateien, jedoch geht die Ordner Struktur von GitHub verloren. 
Siehe Screenshot:
![struktur](https://cloud.githubusercontent.com/assets/12449001/8511088/4f8e3fe4-2308-11e5-9bed-6a868495021e.png)

So ist es nicht wirklich möglich den Beispielen im Buch zu folgen. Denn ich müsste die Namen quasi erraten bzw. alles durchschauen.

Wie kann ich denn das Repository so importieren, dass die Ordnerstruktur erhalten bleibt? Also für jedes Kapitel einen Ordner.

**Comment by dukescript** [comment]
Hallo,

danke für den Hinweis. Ich fürchte, das geht im Moment nicht anders. Im Moment schlage ich als Workaround vor die Projekte einzeln zum jeweiligen Kapitel zu öffnen. Ich werde versuchen die Projekte baldmöglichst umzubenennen. Dann ist die Zuordnung einfacher.

Viele Grüße

Anton Epple
